// * Contains a list of the OpenGL functions that will be loaded at runtime.
//   The macro OpenGLFunction must be #define'd before this header is included, then #undef'd after.
// * This macro can be defined to automate the declaring of global variables used to store the function
//   addresses or, be used to automate the population of these global variables with the correct function
//   addresses.

OpenGLFunction(Viewport, VIEWPORT)
OpenGLFunction(GetString, GETSTRING)
OpenGLFunction(GetStringi, GETSTRINGI)
OpenGLFunction(GetIntegerv, GETINTEGERV)
OpenGLFunction(ClearColor, CLEARCOLOR)
OpenGLFunction(Clear, CLEAR)
OpenGLFunction(CreateShader, CREATESHADER)
OpenGLFunction(ShaderSource, SHADERSOURCE)
OpenGLFunction(CompileShader, COMPILESHADER)
OpenGLFunction(AttachShader, ATTACHSHADER)
OpenGLFunction(GetShaderiv, GETSHADERIV)
OpenGLFunction(GetShaderInfoLog, GETSHADERINFOLOG)
OpenGLFunction(CreateProgram, CREATEPROGRAM)
OpenGLFunction(LinkProgram, LINKPROGRAM)
OpenGLFunction(ValidateProgram, VALIDATEPROGRAM)
OpenGLFunction(GetProgramiv, GETPROGRAMIV)
OpenGLFunction(GetProgramInfoLog, GETPROGRAMINFOLOG)
OpenGLFunction(DeleteShader, DELETESHADER)
OpenGLFunction(Enable, ENABLE)
OpenGLFunction(DebugMessageCallback, DEBUGMESSAGECALLBACK)
OpenGLFunction(DebugMessageControl, DEBUGMESSAGECONTROL)

OpenGLFunction(UseProgram, USEPROGRAM)
OpenGLFunction(GenVertexArrays, GENVERTEXARRAYS)
OpenGLFunction(BindVertexArray, BINDVERTEXARRAY)
OpenGLFunction(GenBuffers, GENBUFFERS)
OpenGLFunction(BindBuffer, BINDBUFFER)
OpenGLFunction(BufferData, BUFFERDATA)
OpenGLFunction(GetAttribLocation, GETATTRIBLOCATION)
OpenGLFunction(EnableVertexAttribArray, ENABLEVERTEXATTRIBARRAY)
OpenGLFunction(VertexAttribPointer, VERTEXATTRIBPOINTER)
OpenGLFunction(GetUniformLocation, GETUNIFORMLOCATION)
OpenGLFunction(UniformMatrix4fv, UNIFORMMATRIX4FV)
OpenGLFunction(DrawArrays, DRAWARRAYS)
OpenGLFunction(DrawElements, DRAWELEMENTS)
OpenGLFunction(ReadPixels, READPIXELS)
OpenGLFunction(BlendFunc, BLENDFUNC)
OpenGLFunction(Scissor, SCISSOR)

OpenGLFunction(GenTextures, GENTEXTURES)
OpenGLFunction(ActiveTexture, ACTIVETEXTURE)
OpenGLFunction(BindTexture, BINDTEXTURE)
OpenGLFunction(TexParameteri, TEXPARAMETERI)
OpenGLFunction(TexImage2D, TEXIMAGE2D)
OpenGLFunction(PixelStorei, PIXELSTOREI)
OpenGLFunction(DeleteTextures, DELETETEXTURES)
